export const categories = [
  { name: 'ACG', total: 19, url: 'https://apkmody.io/games/acg' },
  { name: 'Action', total: 4435, url: 'https://apkmody.io/games/action' },
  { name: 'Adventure', total: 3002, url: 'https://apkmody.io/games/adventure' },
  { name: 'Arcade', total: 3065, url: 'https://apkmody.io/games/arcade' },
  {
    name: 'BeautifulGirl',
    total: 8,
    url: 'https://apkmody.io/games/beautifulgirl',
  },
  { name: 'Board', total: 1156, url: 'https://apkmody.io/games/board' },
  { name: 'Card', total: 1235, url: 'https://apkmody.io/games/card' },
  { name: 'Casual', total: 4489, url: 'https://apkmody.io/games/casual' },
  { name: 'Chess', total: 163, url: 'https://apkmody.io/games/chess' },
  { name: 'Console', total: 7, url: 'https://apkmody.io/games/console' },
  {
    name: 'Educational',
    total: 2632,
    url: 'https://apkmody.io/games/educational',
  },
  { name: 'Horror', total: 20, url: 'https://apkmody.io/games/horror' },
  {
    name: 'Multiplayer',
    total: 62,
    url: 'https://apkmody.io/games/multiplayer',
  },
  { name: 'Music', total: 503, url: 'https://apkmody.io/games/music' },
  { name: 'NSFW', total: 11, url: 'https://apkmody.io/games/nsfw' },
  { name: 'OpenWorld', total: 20, url: 'https://apkmody.io/games/openworld' },
  { name: 'Puzzle', total: 4126, url: 'https://apkmody.io/games/puzzle' },
  { name: 'RPG', total: 3119, url: 'https://apkmody.io/games/rpg' },
  { name: 'Racing', total: 1780, url: 'https://apkmody.io/games/racing' },
  { name: 'Shooter', total: 37, url: 'https://apkmody.io/games/shooter' },
  {
    name: 'Simulation',
    total: 4808,
    url: 'https://apkmody.io/games/simulation',
  },
  { name: 'Sports', total: 1121, url: 'https://apkmody.io/games/sports' },
  { name: 'Strategy', total: 2685, url: 'https://apkmody.io/games/strategy' },
  { name: 'Survival', total: 12, url: 'https://apkmody.io/games/survival' },
  { name: 'Business', total: 37, url: 'https://apkmody.io/apps/business' },
  {
    name: 'Communication',
    total: 62,
    url: 'https://apkmody.io/apps/communication',
  },
  { name: 'Education', total: 170, url: 'https://apkmody.io/apps/education' },
  {
    name: 'Entertainment',
    total: 109,
    url: 'https://apkmody.io/apps/entertainment',
  },
  { name: 'Family', total: 1, url: 'https://apkmody.io/apps/family' },
  { name: 'Life', total: 167, url: 'https://apkmody.io/apps/life' },
  { name: 'News', total: 25, url: 'https://apkmody.io/apps/news' },
  {
    name: 'Photography',
    total: 189,
    url: 'https://apkmody.io/apps/photography',
  },
  { name: 'Social', total: 41, url: 'https://apkmody.io/apps/social' },
  { name: 'SportsLive', total: 41, url: 'https://apkmody.io/apps/sportslive' },
  { name: 'Tools', total: 552, url: 'https://apkmody.io/apps/tools' },
  { name: 'Traffic', total: 27, url: 'https://apkmody.io/apps/traffic' },
  {
    name: 'Video&Music',
    total: 314,
    url: 'https://apkmody.io/apps/videomusic',
  },
  { name: 'Weather', total: 120, url: 'https://apkmody.io/apps/weather' },
];
